<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { storeToRefs } from 'pinia';
import PlatformHeader from '../components/PlatformHeader.vue';
import TransportMap from '../components/TransportMap.vue';
import { api } from '../services/api.js';
import { usePlatformStore, useUiStore } from '../stores/platform.js';

const platform=usePlatformStore(),ui=useUiStore(),route=useRoute(),router=useRouter();
const {mapData}=storeToRefs(platform);const bootstrap=reactive({earthquakeScenarios:[],debrisScenarios:[],regions:[],recentTasks:[],assetCount:0});
const mode=ref(route.query.type==='debris'?'DEBRIS_FLOW':'EARTHQUAKE'),scenarioId=ref(null),form=reactive({}),result=ref(null),loading=ref(false),filter=ref('ALL'),bottom=ref('damage'),mapRef=ref();
const logs=ref([]);const label=computed(()=>mode.value==='EARTHQUAKE'?'地震':'泥石流');const scenarios=computed(()=>mode.value==='EARTHQUAKE'?bootstrap.earthquakeScenarios:bootstrap.debrisScenarios);const scenario=computed(()=>scenarios.value.find(x=>Number(x.id)===Number(scenarioId.value))||scenarios.value[0]||{});
const visibleAssets=computed(()=>!result.value?[]:(result.value.assets||[]).filter(x=>filter.value==='ALL'||x.damageState===filter.value||(filter.value==='PENDING_DATA'&&x.passabilityStatus==='PENDING_DATA')));
const mapAssets=computed(()=>result.value?(result.value.assets||[]).map(x=>({...x,id:x.assetId,status:x.passabilityStatus})):[]);
const summary=computed(()=>{if(!result.value)return[];let extra={};try{extra=typeof result.value.summaryJson==='string'?JSON.parse(result.value.summaryJson):result.value.summaryJson||{}}catch{}return mode.value==='EARTHQUAKE'?[['PGA',Number(result.value.maxIntensity||0).toFixed(3),'g'],['影响半径',Number(result.value.influenceRadiusKm||0).toFixed(1),'km'],['道路影响',Number(result.value.affectedRoadLengthKm||0).toFixed(1),'km'],['受影响桥隧',Number(result.value.affectedBridgeCount||0)+Number(result.value.affectedTunnelCount||0),'处']]:[['发生概率',(Number(result.value.occurrenceProbability||0)*100).toFixed(1),'%'],['最大流速',Number(extra.maxFlowSpeedMs||0).toFixed(1),'m/s'],['最大流深',Number(extra.maxFlowDepthM||0).toFixed(1),'m'],['道路影响',Number(result.value.affectedRoadLengthKm||0).toFixed(1),'km']]});
const checks=computed(()=>[[Boolean(scenario.value.id),'已选择灾害场景方案'],[Boolean(form.longitude&&form.latitude),'已设置灾害源位置'],[bootstrap.assetCount>0,`已加载 ${bootstrap.assetCount||0} 处桥隧设施`]]);
function addLog(text){logs.value.unshift({time:new Date().toLocaleTimeString('zh-CN',{hour12:false}),text})}
function scenarioValues(s){return mode.value==='EARTHQUAKE'?{taskName:'地震风险评估任务',scenarioId:s.id,regionCode:s.regionCode,intensityDegree:String(s.intensityDegree||'VII').replace('度',''),pgaG:s.pgaG??.2,intensityMeasure:s.intensityMeasure||'PGA',durationS:s.durationS??25,magnitudeMw:s.magnitudeMw??6.5,siteCategory:String(s.siteCategory||'II').replace('类',''),influenceRadiusKm:Math.max(20,Number(s.magnitudeMw||6.5)*9),longitude:s.longitude??106.55,latitude:s.latitude??29.56}:{taskName:'泥石流风险评估任务',scenarioId:s.id,regionCode:s.regionCode,rainfallDurationH:s.rainfallDurationH??24,averageRainfallMmH:s.averageRainfallMmH??10,accumulatedRainfallMm:s.accumulatedRainfallMm??240,antecedentRainfallMm:s.antecedentRainfallMm??80,catchmentAreaKm2:s.catchmentAreaKm2??5.5,averageSlopeDegree:s.averageSlopeDegree??28,channelCondition:s.channelCondition||'沟道发育',looseMaterialLevel:s.looseMaterialLevel||'中等',soilMoistureLevel:s.soilMoistureLevel||'潮湿',influenceRadiusKm:15,longitude:s.longitude??107.76,latitude:s.latitude??29.33}}
function applyScenario(){Object.assign(form,scenarioValues(scenario.value))}
watch(scenarioId,applyScenario);watch(mode,()=>{scenarioId.value=(scenarios.value.find(x=>x.isDefault)||scenarios.value[0])?.id;filter.value='ALL';bottom.value=mode.value==='EARTHQUAKE'?'damage':'derivation';result.value=null;router.replace({name:'disaster',query:{type:mode.value==='EARTHQUAKE'?'earthquake':'debris'}})});
async function run(){loading.value=true;addLog(`正在计算${label.value}灾害强度。`);try{result.value=await api('/disaster/evaluate',{method:'POST',body:JSON.stringify({...form,hazardType:mode.value,scenarioId:Number(scenarioId.value)})});platform.rememberTask('disaster',{id:result.value.id,taskCode:result.value.taskCode,taskName:result.value.taskName,moduleType:mode.value,status:'SUCCESS'});addLog(`评估完成：风险等级 ${result.value.riskLevel}。`);ui.toast(`${label.value}评估完成`,'success')}catch(e){addLog('评估失败：'+e.message);ui.toast(e.message)}finally{loading.value=false}}
async function restore(id){if(!id)return;try{result.value=await api(`/disaster/tasks/${id}`);ui.toast('历史结果已恢复','success')}catch(e){ui.toast(e.message)}}
function reset(){result.value=null;applyScenario();mapRef.value?.reset();addLog(`已重置${label.value}评估。`)}
onMounted(async()=>{try{const data=await api('/disaster/bootstrap');Object.assign(bootstrap,data);await Promise.all([platform.loadMap('regions'),platform.loadMap('roads')]);scenarioId.value=(scenarios.value.find(x=>x.isDefault)||scenarios.value[0])?.id;applyScenario();addLog(`已读取 ${scenarios.value.length} 套场景。`)}catch(e){ui.toast('灾害评估后台尚未连接');addLog(e.message)}});
</script>

<template><div class="disaster-workbench"><PlatformHeader/><main class="heavy-main disaster-main">
<aside class="heavy-column heavy-left-column"><section class="tech-panel scenario-panel"><h2 class="tech-panel-title">{{ label }}任务与场景</h2><span class="demo-badge">Pinia 数据</span><label class="field-label">任务名称<input v-model="form.taskName"></label><label class="field-label">场景方案<select v-model="scenarioId"><option v-for="s in scenarios" :key="s.id" :value="s.id">{{ s.scenarioName }}{{ s.isDefault?'（默认）':'' }}</option></select></label><div class="scenario-brief"><strong>{{ scenario.scenarioName||'暂无场景' }}</strong><span>{{ scenario.regionName||'未设置区域' }}</span></div><button class="text-action" @click="applyScenario">恢复当前方案参数</button></section>
<section class="tech-panel parameter-panel"><h2 class="tech-panel-title">{{ mode==='EARTHQUAKE'?'地震输入参数':'降雨与环境输入' }}</h2><div class="disaster-parameter-form"><template v-if="mode==='EARTHQUAKE'"><label class="field-label">地震烈度<select v-model="form.intensityDegree"><option v-for="x in ['VI','VII','VIII','IX']" :key="x">{{ x }}</option></select></label><label class="field-label">PGA(g)<input v-model.number="form.pgaG" type="number" step="0.01"></label><label class="field-label">震级 Mw<input v-model.number="form.magnitudeMw" type="number" step="0.1"></label><label class="field-label">持续时间(s)<input v-model.number="form.durationS" type="number"></label><label class="field-label">场地类别<select v-model="form.siteCategory"><option v-for="x in ['I','II','III','IV']" :key="x">{{ x }}</option></select></label></template><template v-else><label class="field-label">降雨历时(h)<input v-model.number="form.rainfallDurationH" type="number"></label><label class="field-label">平均雨强(mm/h)<input v-model.number="form.averageRainfallMmH" type="number"></label><label class="field-label">累计降雨(mm)<input v-model.number="form.accumulatedRainfallMm" type="number"></label><label class="field-label">平均坡度(°)<input v-model.number="form.averageSlopeDegree" type="number"></label><label class="field-label">沟道条件<select v-model="form.channelCondition"><option>沟道不发育</option><option>沟道一般</option><option>沟道发育</option></select></label><label class="field-label">松散物源<select v-model="form.looseMaterialLevel"><option>较少</option><option>中等</option><option>丰富</option></select></label></template><div class="parameter-location-row"><label class="field-label">经度<input v-model.number="form.longitude" type="number" step="0.0001"></label><label class="field-label">纬度<input v-model.number="form.latitude" type="number" step="0.0001"></label></div></div></section>
<section class="tech-panel disaster-run-panel"><h2 class="tech-panel-title">分析控制</h2><div class="data-check-list"><div v-for="c in checks" :key="c[1]" class="data-check" :class="{ok:c[0]}"><i></i><span>{{ c[1] }}</span></div></div><div class="run-actions"><button class="primary-run-button" :disabled="loading" @click="run">{{ loading?'分析中…':`开始${label}评估` }}</button><button class="secondary-run-button" @click="reset">重置</button></div><div class="task-status"><span>当前状态</span><strong :data-state="result?'success':'idle'">{{ result?'评估完成':'未开始' }}</strong></div><div class="history-restore-row"><select @change="restore($event.target.value)"><option value="">选择历史任务</option><option v-for="t in bootstrap.recentTasks.filter(x=>x.moduleType===mode&&x.status==='SUCCESS')" :key="t.id" :value="t.id">{{ t.taskName }}</option></select></div></section></aside>
<section class="heavy-center-column"><section class="heavy-map-panel disaster-map-panel"><TransportMap ref="mapRef" :regions="mapData.regions" :roads="mapData.roads" :assets="mapAssets" :road-results="result?.roads||[]"/><div class="map-grid-overlay"></div><div class="disaster-mode-switch"><button :class="{'is-active':mode==='EARTHQUAKE'}" @click="mode='EARTHQUAKE'">地震评估</button><button :class="{'is-active':mode==='DEBRIS_FLOW'}" @click="mode='DEBRIS_FLOW'">泥石流评估</button></div><div class="heavy-map-caption"><span class="pulse-dot"></span><span>{{ label }}评估 · {{ result?.riskLevel||'待配置' }}</span></div><div class="heavy-map-tools"><button @click="mapRef.zoomIn()">＋</button><button @click="mapRef.zoomOut()">−</button><button @click="mapRef.reset()">⌂</button></div></section><section class="heavy-bottom-panel"><div class="bottom-tabs"><button v-for="x in [['damage','损伤分布'],['roads','道路影响'],['derivation','推演过程'],['logs','任务日志']]" :key="x[0]" :class="{'is-active':bottom===x[0]}" @click="bottom=x[0]">{{ x[1] }}</button></div><div v-if="bottom==='logs'" class="task-log-list"><div v-for="l in logs" :key="l.time+l.text" class="task-log"><time>{{ l.time }}</time><i></i><span>{{ l.text }}</span></div></div><div v-else-if="bottom==='roads'" class="road-impact-grid"><div v-for="s in ['PASS','CONDITIONAL','BLOCKED']" :key="s"><span>{{ s }}</span><strong>{{ result?.roads?.filter(x=>x.passabilityStatus===s).length||0 }}条</strong></div></div><div v-else class="damage-chart-row"><div v-for="s in ['DS0','DS1','DS2','DS3','DS4']" :key="s" class="damage-chart-item"><strong>{{ s }}</strong><span>{{ result?.damageDistribution?.find(x=>x.name===s)?.value||0 }}处</span></div></div></section></section>
<aside class="heavy-column heavy-right-column"><section class="tech-panel disaster-summary-panel"><h2 class="tech-panel-title">{{ label }}影响摘要</h2><div class="disaster-risk-orbit" :data-risk="result?.riskLevel||'idle'"><span>综合风险</span><strong>{{ result?.riskLevel||'等待评估' }}</strong><small>{{ result?Number(result.riskScore||0).toFixed(1)+'分':'--' }}</small></div><div class="disaster-summary-metrics"><div v-for="m in summary" :key="m[0]"><span>{{ m[0] }}</span><strong>{{ m[1] }}</strong><small>{{ m[2] }}</small></div></div></section><section class="tech-panel disaster-result-panel"><h2 class="tech-panel-title">桥隧易损性结果</h2><div class="asset-filter-row"><button v-for="f in ['ALL','DS0','DS1','DS2','DS3','DS4','PENDING_DATA']" :key="f" :class="{'is-active':filter===f}" @click="filter=f">{{ f }}</button></div><div class="heavy-asset-list scroll-region"><article v-for="a in visibleAssets" :key="a.assetId" class="heavy-asset-item" :data-status="a.passabilityStatus"><i class="status-bar"></i><div><strong>{{ a.assetName }}</strong><small>{{ a.assessmentReason }}</small></div><div><span class="damage-badge">{{ a.damageState }}</span><span class="asset-state">{{ a.passabilityStatus }}</span></div></article><p v-if="!visibleAssets.length" class="empty-tip">尚无评估结果。</p></div></section><section class="tech-panel disaster-advice-panel"><h2 class="tech-panel-title">风险清单与处置建议</h2><div class="recommendation-list"><article v-for="a in result?.assets?.filter(x=>['DS3','DS4'].includes(x.damageState)).slice(0,3)||[]" :key="a.assetId" class="recommendation-item warning"><strong>{{ a.assetName }} · {{ a.damageState }}</strong><p>{{ a.recommendedAction }}</p></article><p v-if="!result" class="empty-tip">完成评估后展示处置建议。</p></div></section></aside>
</main></div></template>
