<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue';
import { storeToRefs } from 'pinia';
import PlatformHeader from '../components/PlatformHeader.vue';
import TransportMap from '../components/TransportMap.vue';
import { adminApi } from '../services/api.js';
import { usePlatformStore, useUiStore } from '../stores/platform.js';

const platform=usePlatformStore(), ui=useUiStore();
const {vehicles,assets,mapData}=storeToRefs(platform);
const mapRef=ref(), selectedProfileId=ref(null), editOpen=ref(false), loading=ref(false), result=ref(null), filter=ref('ALL'), bottomTab=ref('routes'), layerOpen=ref(false);
const form=reactive({taskName:'重车通行评估任务',origin:'渝中区 · 解放碑',destination:'江北区 · 观音桥',avoidBlocked:true,allowConditional:true,preference:'SAFETY',grossWeightTon:100,vehicleLengthM:18,vehicleWidthM:3.2,vehicleHeightM:4.5,axleCount:6,plannedSpeedKmh:30});
const logs=ref([{time:new Date().toLocaleTimeString('zh-CN',{hour12:false}),text:'Vue 重车评估工作台已初始化。'}]);
const detailCache=new Map();
const label=s=>({PASS:'可通行',CONDITIONAL:'条件通行',BLOCKED:'禁止通行',PENDING_DATA:'待核查'})[s]||s;
const statusClass=s=>({PASS:'pass',CONDITIONAL:'conditional',BLOCKED:'blocked',PENDING_DATA:'pending'})[s]||'pending';
const selectedProfile=computed(()=>vehicles.value.find(x=>Number(x.id)===Number(selectedProfileId.value))||vehicles.value[0]||{});
const visibleRows=computed(()=>!result.value?[]:result.value.rows.filter(r=>filter.value==='ALL'||r.status===filter.value));
const mapAssets=computed(()=>assets.value.map(a=>({...a,status:result.value?.rows.find(r=>Number(r.assetId)===Number(a.id))?.status})));
const checks=computed(()=>[[Boolean(selectedProfile.value.profileName),'已选择重车参数方案'],[Boolean(form.origin.trim()&&form.destination.trim()),'已设置起点与终点'],[assets.value.length>0,`已加载 ${assets.value.length} 处评估桥隧`],[assets.value.some(x=>Number(x.bindingCount)>0),'桥隧路网绑定数据可用']]);
const conclusion=computed(()=>({PASS:['建议通行','沿线关键指标满足当前规则'],CONDITIONAL:['条件通行','请落实限速、复核或绕行建议'],BLOCKED:['不建议通行','当前方案存在限制条件'],PENDING_DATA:['数据待核查','设施参数不足']})[result.value?.conclusion]||['等待评估','请设置车辆与起终点']);
function addLog(text){logs.value.unshift({time:new Date().toLocaleTimeString('zh-CN',{hour12:false}),text});logs.value=logs.value.slice(0,12)}
function applyProfile(){const p=selectedProfile.value;Object.assign(form,{grossWeightTon:Number(p.grossWeightTon||100),vehicleLengthM:Number(p.vehicleLengthM||18),vehicleWidthM:Number(p.vehicleWidthM||3.2),vehicleHeightM:Number(p.vehicleHeightM||4.5),axleCount:Number(p.axleCount||6),plannedSpeedKmh:Number(p.plannedSpeedKmh||30)})}
watch(selectedProfileId,applyProfile);
async function detail(asset){if(detailCache.has(asset.id))return detailCache.get(asset.id);const value=await adminApi(`/assets/${asset.id}`);detailCache.set(asset.id,value);return value}
async function judge(asset){let full;try{full=await detail(asset)}catch{return{assetId:asset.id,status:'PENDING_DATA',reason:'无法读取设施专有参数。',action:'请检查后台连接。'}}const d=full?.detail||{};if(!Object.keys(d).length)return{assetId:asset.id,status:'PENDING_DATA',reason:'缺少设施专有参数。',action:'请在数据管理中补充参数。'};if((asset.serviceStatus||full.serviceStatus)==='CLOSED')return{assetId:asset.id,status:'BLOCKED',reason:'设施当前状态为关闭。',action:'请选择绕行路线。'};if(asset.assetType==='BRIDGE'){const cap=Number(d.design_load_ton);if(!cap)return{assetId:asset.id,status:'PENDING_DATA',reason:'缺少桥梁设计荷载参数。',action:'补充设计荷载。'};if(form.grossWeightTon>cap)return{assetId:asset.id,status:'BLOCKED',reason:`车辆总重 ${form.grossWeightTon}t 超过设计荷载 ${cap}t。`,action:'避开该桥梁。'};if(form.grossWeightTon/cap>=.85)return{assetId:asset.id,status:'CONDITIONAL',reason:'荷载利用率接近阈值。',action:'建议限速并复核轴载。'};return{assetId:asset.id,status:'PASS',reason:'车辆荷载满足当前规则。',action:'可按计划通行。'}}const v=Number(d.vertical_clearance_m),h=Number(d.horizontal_clearance_m);if(!v||!h)return{assetId:asset.id,status:'PENDING_DATA',reason:'缺少隧道净空参数。',action:'补充断面参数。'};if(form.vehicleHeightM>v||form.vehicleWidthM>h)return{assetId:asset.id,status:'BLOCKED',reason:'车辆外廓超过隧道净空。',action:'请选择绕行路线。'};if(form.vehicleHeightM>v*.9||form.vehicleWidthM>h*.9)return{assetId:asset.id,status:'CONDITIONAL',reason:'车辆外廓接近净空阈值。',action:'建议低速通过。'};return{assetId:asset.id,status:'PASS',reason:'车辆外廓满足隧道断面规则。',action:'可按计划通行。'}}
async function run(){if(!form.origin.trim()||!form.destination.trim())return ui.toast('请填写起点和终点');loading.value=true;addLog('正在执行荷载与净空规则检查。');const rows=await Promise.all(assets.value.map(judge));const count=s=>rows.filter(x=>x.status===s).length;const blocked=count('BLOCKED'),conditional=count('CONDITIONAL'),pending=count('PENDING_DATA');let c=pending===rows.length?'PENDING_DATA':'PASS';if((blocked&&!form.avoidBlocked)||(conditional&&!form.allowConditional))c='BLOCKED';else if(blocked||conditional)c='CONDITIONAL';result.value={rows,pass:count('PASS'),blocked,conditional,pending,conclusion:c,recommendedDistance:Number((25.8+blocked*3.1+conditional*.8).toFixed(1)),alternativeDistance:Number((33.6+conditional*.7).toFixed(1))};mapRef.value?.drawRoutes([{points:[[29.5634,106.5518],[29.574,106.578],[29.5901,106.6055]],style:{color:'#45e4ff',weight:5}},{points:[[29.5634,106.5518],[29.548,106.534],[29.575,106.562],[29.5901,106.6055]],style:{color:'#a187ff',weight:3,dashArray:'7 8'}}]);addLog(`评估完成：${result.value.pass}处可通行、${conditional}处条件通行、${blocked}处禁止通行。`);loading.value=false;ui.toast('重车通行评估完成','success')}
function reset(){result.value=null;filter.value='ALL';mapRef.value?.drawRoutes([]);mapRef.value?.reset();addLog('已重置本次评估结果。')}
onMounted(async()=>{try{await Promise.all([platform.loadCatalogs(),platform.loadMap('roads')]);selectedProfileId.value=(platform.defaultVehicle.id||vehicles.value[0]?.id);applyProfile()}catch(e){ui.toast('后台未连接，暂不能读取车辆和桥隧数据');addLog('后台数据加载失败：'+e.message)}});
</script>

<template><div class="heavy-workbench"><PlatformHeader/><main class="heavy-main">
<aside class="heavy-column heavy-left-column"><section class="tech-panel heavy-task-panel"><h2 class="tech-panel-title">重车任务配置</h2><span class="demo-badge">Pinia 数据</span><label class="field-label">任务名称<input v-model="form.taskName" maxlength="100"></label><label class="field-label">重车参数方案<select v-model="selectedProfileId"><option v-for="p in vehicles" :key="p.id" :value="p.id">{{ p.profileName }}{{ p.isDefault?'（默认）':'' }}</option></select></label><div class="vehicle-brief"><span class="vehicle-brief-icon">▰</span><div><strong>{{ selectedProfile.profileName||'本次临时参数' }}</strong><small>{{ form.grossWeightTon }}t · {{ form.axleCount }}轴 · {{ form.vehicleLengthM }} × {{ form.vehicleWidthM }} × {{ form.vehicleHeightM }}m</small></div></div><button class="text-action" @click="editOpen=!editOpen">编辑本次参数</button><div v-show="editOpen" class="vehicle-edit-grid"><label>总车重(t)<input v-model.number="form.grossWeightTon" type="number" step="0.1"></label><label>长度(m)<input v-model.number="form.vehicleLengthM" type="number" step="0.1"></label><label>宽度(m)<input v-model.number="form.vehicleWidthM" type="number" step="0.1"></label><label>高度(m)<input v-model.number="form.vehicleHeightM" type="number" step="0.1"></label><label>轴数<input v-model.number="form.axleCount" type="number"></label><label>计划速度<input v-model.number="form.plannedSpeedKmh" type="number"></label></div></section>
<section class="tech-panel route-config-panel"><h2 class="tech-panel-title">起终点与路线约束</h2><div class="endpoint-row"><span class="endpoint-mark start">起</span><label><span>起点</span><input v-model="form.origin"></label></div><button class="swap-endpoints" @click="[form.origin,form.destination]=[form.destination,form.origin]">⇅</button><div class="endpoint-row"><span class="endpoint-mark end">终</span><label><span>终点</span><input v-model="form.destination"></label></div><div class="route-options"><label class="check-row"><input v-model="form.avoidBlocked" type="checkbox"><span>避开禁止通行设施</span></label><label class="check-row"><input v-model="form.allowConditional" type="checkbox"><span>允许条件通行</span></label><label class="field-label compact">路线偏好<select v-model="form.preference"><option value="SAFETY">最少风险</option><option value="DISTANCE">最短距离</option><option value="TIME">最短时间</option></select></label></div></section>
<section class="tech-panel run-panel"><h2 class="tech-panel-title">评估控制</h2><div class="data-check-list"><div v-for="c in checks" :key="c[1]" class="data-check" :class="{ok:c[0]}"><i></i><span>{{ c[1] }}</span></div></div><div class="run-actions"><button class="primary-run-button" :disabled="loading" @click="run">{{ loading?'评估中…':'开始通行评估' }}</button><button class="secondary-run-button" @click="reset">重置</button></div><div class="task-status"><span>当前状态</span><strong :data-state="result?'success':'idle'">{{ result?'评估完成':'未开始' }}</strong></div></section></aside>
<section class="heavy-center-column"><section class="heavy-map-panel"><TransportMap ref="mapRef" :roads="mapData.roads" :assets="mapAssets" :center="[29.61,106.56]" :zoom="10" @asset-click="mapRef.focus($event.latitude,$event.longitude)"/><div class="map-grid-overlay"></div><div class="heavy-map-caption"><span class="pulse-dot"></span><span>{{ result?`${form.origin} → ${form.destination} · 规则模拟路径`:'重车通行评估 · 待配置' }}</span></div><div class="heavy-map-tools"><button @click="mapRef.zoomIn()">＋</button><button @click="mapRef.zoomOut()">−</button><button @click="mapRef.reset()">⌂</button><button @click="layerOpen=!layerOpen">▱</button></div><div class="heavy-layer-popover" :class="{'is-open':layerOpen}"><strong>图层控制</strong><label><input type="checkbox" checked @change="mapRef.toggleLayer('roads',$event.target.checked)"> 路网</label><label><input type="checkbox" checked @change="mapRef.toggleLayer('assets',$event.target.checked)"> 桥隧</label><button @click="mapRef.setBase('satellite')">卫星地图</button><button @click="mapRef.setBase('electronic')">电子地图</button></div></section><section class="heavy-bottom-panel"><div class="bottom-tabs"><button :class="{'is-active':bottomTab==='routes'}" @click="bottomTab='routes'">路径方案</button><button :class="{'is-active':bottomTab==='logs'}" @click="bottomTab='logs'">任务日志</button></div><div v-if="bottomTab==='logs'" class="task-log-list"><div v-for="l in logs" :key="l.time+l.text" class="task-log"><i></i><time>{{ l.time }}</time><span>{{ l.text }}</span></div></div><div v-else-if="result" class="route-plan-grid"><article class="route-plan-card is-selected"><header><strong>安全推荐路径</strong><span>推荐</span></header><div class="route-plan-stats"><div>距离<strong>{{ result.recommendedDistance }}km</strong></div><div>时间<strong>{{ Math.round(result.recommendedDistance/Math.max(form.plannedSpeedKmh,15)*60) }}min</strong></div></div></article><article class="route-plan-card"><header><strong>备选绕行路径</strong></header><div class="route-plan-stats"><div>距离<strong>{{ result.alternativeDistance }}km</strong></div></div></article></div><p v-else class="empty-tip">评估完成后显示路径方案。</p></section></section>
<aside class="heavy-column heavy-right-column"><section class="tech-panel conclusion-panel"><h2 class="tech-panel-title">综合通行结论</h2><div class="conclusion-status" :data-status="result?.conclusion?.toLowerCase()||'idle'"><span class="conclusion-orbit"></span><strong>{{ conclusion[0] }}</strong><small>{{ conclusion[1] }}</small></div><div class="result-metrics"><div><span>推荐路径</span><strong>{{ result?.recommendedDistance??'--' }}</strong><small>km</small></div><div><span>沿线桥隧</span><strong>{{ result?.rows.length??'--' }}</strong><small>处</small></div></div><div v-if="result" class="status-distribution"><span>通行 <b>{{ result.pass }}</b></span><span>条件 <b>{{ result.conditional }}</b></span><span>禁止 <b>{{ result.blocked }}</b></span></div></section><section class="tech-panel asset-result-panel"><h2 class="tech-panel-title">沿线桥隧判定</h2><div class="asset-filter-row"><button v-for="f in ['ALL','PASS','CONDITIONAL','BLOCKED','PENDING_DATA']" :key="f" :class="{'is-active':filter===f}" @click="filter=f">{{ f==='ALL'?'全部':label(f) }}</button></div><div class="heavy-asset-list scroll-region"><article v-for="row in visibleRows" :key="row.assetId" class="heavy-asset-item" :data-status="row.status"><i class="status-bar"></i><div><strong>{{ assets.find(a=>a.id==row.assetId)?.assetName }}</strong><small>{{ row.reason }}</small></div><span class="asset-state" :class="statusClass(row.status)">{{ label(row.status) }}</span></article><p v-if="!visibleRows.length" class="empty-tip">尚无评估结果</p></div></section><section class="tech-panel recommendation-panel"><h2 class="tech-panel-title">关键风险与保通建议</h2><div class="recommendation-list"><article v-for="row in result?.rows.filter(x=>x.status!=='PASS').slice(0,3)||[]" :key="row.assetId" class="recommendation-item"><strong>{{ label(row.status) }}</strong><p>{{ row.reason }} {{ row.action }}</p></article><p v-if="!result" class="empty-tip">完成评估后展示建议。</p></div></section></aside>
</main></div></template>
