<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import { storeToRefs } from 'pinia';
import PlatformHeader from '../components/PlatformHeader.vue';
import TransportMap from '../components/TransportMap.vue';
import { api } from '../services/api.js';
import { usePlatformStore, useUiStore } from '../stores/platform.js';

const platform=usePlatformStore(),ui=useUiStore();const {mapData}=storeToRefs(platform);
const bootstrap=reactive({odProfiles:[],recoveryPlans:[],disasterTasks:[],recentTasks:[],network:{}});const form=reactive({taskName:'路网韧性评估任务',odProfileId:null,recoveryPlanId:null,disasterTaskId:null,targetAccessibility:.99,targetTravelTimeRatio:1.05});
const result=ref(null),loading=ref(false),networkState=ref('normal'),networkMetric=ref('status'),bottom=ref('overview'),timeIndex=ref(0),mapRef=ref();const logs=ref([]);
const profile=computed(()=>bootstrap.odProfiles.find(x=>Number(x.id)===Number(form.odProfileId))||{});const plan=computed(()=>bootstrap.recoveryPlans.find(x=>Number(x.id)===Number(form.recoveryPlanId))||{});const disaster=computed(()=>bootstrap.disasterTasks.find(x=>Number(x.id)===Number(form.disasterTaskId))||{});const timeline=computed(()=>result.value?.timeline||[]);const currentTime=computed(()=>timeline.value[timeIndex.value]||{});
const pct=v=>(Number(v||0)*100).toFixed(1)+'%';const checks=computed(()=>[[Boolean(profile.value.id),'已选择OD需求方案'],[Boolean(plan.value.id),'已选择恢复方案'],[Boolean(bootstrap.network?.roadCount),'分析路网数据可用']]);
const roadResults=computed(()=>{if(!result.value||networkState.value==='normal')return[];if(networkState.value!=='recovery')return result.value.roads||[];const max=Number(timeline.value.at(-1)?.timeH||72),t=Number(currentTime.value.timeH||0);return(result.value.roads||[]).map(x=>({...x,remainingCapacityRatio:Number(x.remainingCapacityRatio||1)+(1-Number(x.remainingCapacityRatio||1))*(max?t/max:1)}))});
function addLog(text){logs.value.unshift({time:new Date().toLocaleTimeString('zh-CN',{hour12:false}),text})}
async function run(){loading.value=true;addLog('正在建立正常基准并分析灾后OD可达性。');try{result.value=await api('/resilience/evaluate',{method:'POST',body:JSON.stringify(form)});networkState.value='post';timeIndex.value=0;platform.rememberTask('resilience',{id:result.value.id,taskCode:result.value.taskCode,taskName:result.value.taskName,status:'SUCCESS'});await platform.loadDashboard(true);addLog(`评估完成：可达率 ${pct(result.value.accessibilityRate)}，功能保持 ${pct(result.value.functionRetentionRate)}。`);ui.toast('路网韧性评估完成','success')}catch(e){addLog('评估失败：'+e.message);ui.toast(e.message)}finally{loading.value=false}}
async function restore(id){if(!id)return;try{result.value=await api(`/resilience/tasks/${id}`);networkState.value='post';ui.toast('历史韧性结果已恢复','success')}catch(e){ui.toast(e.message)}}
function reset(){result.value=null;networkState.value='normal';timeIndex.value=0;mapRef.value?.reset();addLog('已重置本次路网韧性评估。')}
onMounted(async()=>{try{Object.assign(bootstrap,await api('/resilience/bootstrap'));await Promise.all([platform.loadMap('regions'),platform.loadMap('roads')]);form.odProfileId=(bootstrap.odProfiles.find(x=>x.isDefault)||bootstrap.odProfiles[0])?.id;form.recoveryPlanId=(bootstrap.recoveryPlans.find(x=>x.isDefault)||bootstrap.recoveryPlans[0])?.id;addLog(`已读取 ${bootstrap.odProfiles.length} 套OD方案。`)}catch(e){ui.toast('路网韧性评估后台尚未连接');addLog(e.message)}});
</script>

<template><div class="resilience-workbench"><PlatformHeader/><main class="heavy-main resilience-main">
<aside class="heavy-column heavy-left-column"><section class="tech-panel baseline-panel"><h2 class="tech-panel-title">评估任务与正常基准</h2><span class="demo-badge">Pinia 数据</span><label class="field-label">任务名称<input v-model="form.taskName"></label><label class="field-label">OD需求方案<select v-model="form.odProfileId"><option v-for="p in bootstrap.odProfiles" :key="p.id" :value="p.id">{{ p.profileName }}{{ p.isDefault?'（默认）':'' }}</option></select></label><div class="baseline-brief"><strong>{{ profile.profileName||'暂无方案' }}</strong><span>{{ profile.description||'等待后台数据' }}</span></div></section>
<section class="tech-panel damage-config-panel"><h2 class="tech-panel-title">灾后路网场景</h2><label class="field-label">灾害评估结果<select v-model="form.disasterTaskId"><option :value="null">预设演示受损路网</option><option v-for="t in bootstrap.disasterTasks" :key="t.id" :value="t.id">{{ t.taskName }} · {{ t.riskLevel }}</option></select></label><div class="capacity-mapping"><div><span>正常</span><strong>η=1.0</strong></div><div><span>条件通行</span><strong>η=0.5</strong></div><div><span>完全中断</span><strong>η=0</strong></div></div><div class="scenario-brief"><strong>{{ disaster.taskName||'预设场景' }}</strong><span>{{ disaster.riskLevel||'未选择灾害任务时使用演示数据' }}</span></div></section>
<section class="tech-panel resilience-control-panel"><h2 class="tech-panel-title">恢复方案与分析控制</h2><label class="field-label">恢复方案<select v-model="form.recoveryPlanId"><option v-for="p in bootstrap.recoveryPlans" :key="p.id" :value="p.id">{{ p.planName }}</option></select></label><div class="threshold-grid"><label>目标可达率<input v-model.number="form.targetAccessibility" type="number" step="0.01"></label><label>旅行时间阈值<input v-model.number="form.targetTravelTimeRatio" type="number" step="0.01"></label></div><div class="data-check-list"><div v-for="c in checks" :key="c[1]" class="data-check" :class="{ok:c[0]}"><i></i><span>{{ c[1] }}</span></div></div><div class="run-actions"><button class="primary-run-button" :disabled="loading" @click="run">{{ loading?'分析中…':'开始韧性评估' }}</button><button class="secondary-run-button" @click="reset">重置</button></div><div class="task-status"><span>当前状态</span><strong :data-state="result?'success':'idle'">{{ result?'评估完成':'未开始' }}</strong></div><div class="history-restore-row"><select @change="restore($event.target.value)"><option value="">选择历史任务</option><option v-for="t in bootstrap.recentTasks" :key="t.id" :value="t.id">{{ t.taskName }}</option></select></div></section></aside>
<section class="heavy-column heavy-center-column"><section class="heavy-map-panel resilience-map-panel"><TransportMap ref="mapRef" :regions="mapData.regions" :roads="mapData.roads" :road-results="roadResults"/><div class="resilience-state-switch"><button v-for="s in [['normal','正常状态'],['post','灾后初始'],['recovery','恢复过程']]" :key="s[0]" :class="{'is-active':networkState===s[0]}" @click="networkState=s[0]">{{ s[1] }}</button></div><div class="resilience-metric-switch"><button v-for="m in [['status','通行状态'],['capacity','剩余能力'],['vc','饱和度']]" :key="m[0]" :class="{'is-active':networkMetric===m[0]}" @click="networkMetric=m[0]">{{ m[1] }}</button></div><div class="heavy-map-caption"><span class="pulse-dot"></span><span>{{ networkState==='normal'?'正常路网基准':networkState==='post'?'灾后初始路网':`恢复过程 · ${currentTime.timeH||0}h` }} · {{ result?.resilienceLevel||'待评估' }}</span></div><div class="heavy-map-tools"><button @click="mapRef.zoomIn()">＋</button><button @click="mapRef.zoomOut()">−</button><button @click="mapRef.reset()">⌂</button></div><div class="recovery-time-control" :class="{'is-open':networkState==='recovery'&&result}"><span>恢复时刻</span><input v-model.number="timeIndex" type="range" min="0" :max="Math.max(0,timeline.length-1)"><strong>{{ currentTime.timeH||0 }}h</strong></div></section>
<section class="heavy-bottom-panel resilience-bottom-panel"><div class="bottom-tabs"><button v-for="x in [['overview','功能保持结果'],['timeline','恢复曲线'],['od','OD可达性'],['logs','任务日志']]" :key="x[0]" :class="{'is-active':bottom===x[0]}" @click="bottom=x[0]">{{ x[1] }}</button></div><div v-if="bottom==='logs'" class="task-log-list"><div v-for="l in logs" :key="l.time+l.text" class="task-log"><time>{{ l.time }}</time><i></i><span>{{ l.text }}</span></div></div><div v-else-if="bottom==='timeline'" class="timeline-chart"><div v-for="t in timeline" :key="t.timeH" class="timeline-point"><div class="bar" :style="{height:`${Math.max(4,Number(t.functionRetentionRate||0)*68)}px`}"></div><strong>{{ pct(t.functionRetentionRate) }}</strong><span>{{ t.timeH }}h</span></div></div><div v-else-if="bottom==='od'" class="bottom-od-list"><div v-for="o in result?.odResults?.slice(0,8)||[]" :key="o.odDemandId">{{ o.originNode }} → {{ o.destinationNode }}<small>{{ o.reachable?'可达 · 绕行比 '+Number(o.detourRatio||0).toFixed(2):'不可达' }}</small></div></div><div v-else-if="result" class="resilience-overview-grid"><div><span>正常总旅行时间 D₀</span><strong>{{ Number(result.baselineTotalTravelTime||0).toFixed(0) }}</strong></div><div><span>灾后总旅行时间 Dₛ</span><strong>{{ Number(result.postTotalTravelTime||0).toFixed(0) }}</strong></div><div><span>受影响道路里程</span><strong>{{ Number(result.affectedRoadLengthKm||0).toFixed(1) }} km</strong></div><div><span>韧性等级</span><strong>{{ result.resilienceLevel }}</strong></div></div><p v-else class="empty-tip">完成评估后展示结果。</p></section></section>
<aside class="heavy-column heavy-right-column"><section class="tech-panel resilience-summary-panel"><h2 class="tech-panel-title">韧性综合评价</h2><div class="resilience-score-orbit"><span>综合韧性</span><strong>{{ result?.resilienceLevel||'等待评估' }}</strong><small>{{ result?Number(result.resilienceScore||0).toFixed(1)+'分':'--' }}</small></div><div class="resilience-kpi-grid"><div><span>可达率</span><strong>{{ result?pct(result.accessibilityRate):'--' }}</strong></div><div><span>功能保持</span><strong>{{ result?pct(result.functionRetentionRate):'--' }}</strong></div><div><span>恢复时间</span><strong>{{ result?.recoveryTimeH??'--' }}h</strong></div></div></section><section class="tech-panel connectivity-panel"><h2 class="tech-panel-title">孤立节点与不可达OD</h2><div class="connectivity-alert"><strong>{{ result?.unreachableOdCount||0 }}</strong><span>组不可达 OD</span></div><div class="od-result-list scroll-region"><article v-for="o in result?.odResults?.filter(x=>!x.reachable)||[]" :key="o.odDemandId" class="od-result-item unreachable"><strong>{{ o.originNode }} → {{ o.destinationNode }}</strong><small>需求 {{ o.demandVehH }} veh/h</small></article><p v-if="!result" class="empty-tip">评估完成后展示OD结果。</p></div></section><section class="tech-panel critical-road-panel"><h2 class="tech-panel-title">关键道路与抢修建议</h2><div class="critical-road-list scroll-region"><article v-for="r in result?.roads?.filter(x=>Number(x.remainingCapacityRatio)<1).slice(0,8)||[]" :key="r.roadEdgeId" class="critical-road-item"><strong>{{ r.roadName||r.roadRef||`道路 ${r.roadEdgeId}` }}</strong><small>剩余能力 {{ pct(r.remainingCapacityRatio) }}</small></article><p v-if="!result" class="empty-tip">评估完成后生成优先级。</p></div></section></aside>
</main></div></template>
